sudo: false
dist: trusty
cache: pip
language: python
python:
  - "3.6"
  - "2.7"
env:
  global:
    - PYPI_VENDOR_DIR='./tests/pypi/'
    - GIT_ASK_YESNO='false'
  matrix:
    - TEST_SUITE='not install'
      CACHE_NAME=$TRAVIS_PYTHON_VERSION-TEST
    - TEST_SUITE='install'
      RUN_INTEGRATION_TESTS='1'
      PYTEST_ADDOPTS='--cache-clear'
      CACHE_NAME=$TRAVIS_PYTHON_VERSION-INSTALL

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -e . --upgrade --upgrade-strategy=only-if-needed"
  - "pipenv install --deploy --system --dev"

# command to run the dependencies
script:
  - 'if [[ -n "$RUN_INTEGRATION_TESTS" ]]; then rm -fr ~/.cache/pip; fi'
  - 'export PYPI_VENDOR_DIR="$(pwd)/tests/pypi/"'
  - 'pip install -e "$(pwd)" --upgrade'
  - 'pipenv install --dev'
  - 'pipenv run time pytest -v -n 4 --ignore="pipenv/vendor" --ignore="pipenv/patched" -m "$TEST_SUITE" tests'
